server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # AUTH SERVICE (PUBLIC)
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        # POLICY SERVICE (SECURED)
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/api/policies/**
          filters:
            - JwtAuthenticationFilter

        # CLAIMS SERVICE (SECURED)
        - id: claims-service
          uri: lb://CLAIMS-SERVICE
          predicates:
            - Path=/api/claims/**
          filters:
            - JwtAuthenticationFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: this_is_a_very_secret_key_for_smartsure_project_12345