server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # AUTH SERVICE (PUBLIC)
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        # POLICY SERVICE (INCLUDING ADMIN)
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/api/policies/**,/api/admin/policies/**
          filters:
            - JwtAuthenticationFilter

        # CLAIMS SERVICE (USER APIs)
        - id: claims-service
          uri: lb://CLAIMS-SERVICE
          predicates:
            - Path=/api/claims/**
          filters:
            - JwtAuthenticationFilter

        # ADMIN CLAIM ROUTES
        - id: admin-claims-service
          uri: lb://CLAIMS-SERVICE
          predicates:
            - Path=/api/admin/claims/**
          filters:
            - JwtAuthenticationFilter

        # ADMIN REPORTS
        - id: admin-reports-service
          uri: lb://CLAIMS-SERVICE
          predicates:
            - Path=/api/admin/reports
          filters:
            - JwtAuthenticationFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: this_is_a_very_secret_key_for_smartsure_project_12345

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"